os:
  - linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

if: type != pull_request  # do not build anything for PRs

script:
  - flake8
  - coverage run --source drs-filer -m pytest
  - coveralls