version: '3.6'
services:

    drs:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
        command: bash -c "cd /app/drs_filer; gunicorn -c config.py wsgi:app"
        ports:
            - "7777:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        ports:
            - "27017:27017"
        