apiVersion: v1
kind: Service
metadata:
  name: drs-filer
spec:
  ports:
  - name: drs-filer
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: drs-filer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
