{{ if eq .Values.clusterType "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: drs-filer
spec:
  host: {{ .Values.host_name }}
  port:
    targetPort: drs-filer
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: drs-filer
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{ end }}
