{{ if eq .Values.drs_filer.ingress true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drs-filer
spec:
  rules:
    - host: {{ .Values.host_name }}
      http:
        paths:
          - path: /ga4gh/drs/v1
            pathType: Prefix
            backend:
              service:
                name: drs-filer
                port:
                  number: 8080
{{ end }}
