apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-script.js: |
    db = db.getSiblingDB('drsStore');

    // Create the 'objects' and 'service_info' collections
    // Database configuration from https://github.com/elixir-cloud-aai/drs-filer/blob/dev/drs_filer/config.yaml#L10
    db.createCollection('objects')
    db.objects.createIndex(
      { id: 1 },
      { unique: true }
    );
    db.createCollection('service_info');
    db.service_info.createIndex(
      { id: 1 },
      { unique: true}
    );

