server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: False

db:
    host: mongodb
    port: 27017
    dbs:
        drsStore:
            collections:
                objects:
                    indexes:
                        - keys:
                              id: 1
                          options: 
                            'unique': True

api:
    specs:
        - path:
            - api/20200622.383121d.data_repository_service.swagger.yaml
            - api/additional.data_repository_service.swagger.yaml
          append: null
          connexion:
              strict_validation: True
              validate_responses: True
              options:
                  swagger_ui: True
                  serve_spec: True

log:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            class: logging.Formatter
            style: "{"
            format: "[{asctime}: {levelname:<8}] {message} [{name}]"
    handlers:
        console:
            class: logging.StreamHandler
            level: 20
            formatter: standard
            stream: ext://sys.stderr
    root:
        level: 10
        handlers: [console]


exceptions:
    required_members: [['msg'], ['status_code']]
    status_member: ['status_code']
    exceptions: drs_filer.errors.exceptions.exceptions


endpoints:
    objects:
        id_charset: string.ascii_letters + string.digits + ".-_~"
        id_length: 6
    access_methods:
        id_charset: string.ascii_letters + string.digits + ".-_~"
        id_length: 6

